name: llm
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ipython==8.22.2
  - ipykernel==6.29.3
  - ipywidgets==8.1.2
  - python-dotenv==1.0.1
  - numpy==1.26.4
  - pandas==2.2.2
  - pip==24.0
  - pip:
    - langchain==0.1.17
    - langchain-openai==0.1.6
    - openai==1.26.0
