name: llm
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ipython==8.22.2
  - ipykernel==6.29.3
  - ipywidgets==8.1.2
  - python-dotenv==1.0.1
  - numpy==1.26.4
  - pandas==2.2.2
  - beautifulsoup4==4.12.3
  - pip==24.0
  - pip:
    - langchain==0.2.6
    - langchain-community==0.2.6
    - langchain-openai==0.1.13
    - langgraph==0.1.5
    - openai==1.35.8
    - faiss-cpu==1.8.0
    - tavily-python==0.3.3
    - wikipedia==1.4.0
